#声明微服务的端口号
server:
  port: 9001

#声明微服务的名称
spring:
  application:
    name: microservice-user
  #声明数据源
  datasource:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.57.39:3306/jsd20129?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456

  #声明jpa实施正向工程
  jpa:
    #显示sql语句
    show-sql: true
    #生成建表语句
    generate-ddl: true
    #底层数据库是MySQL数据库
    database: mysql

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.57.1:8888/eureka


#  instance:
#    prefer-ip-address: true
